#ifndef TESTMODE 

#else
#pragma once
#include "Exception_CorruptedFile.cpp"
#include "Exception_ExceededParameterLimit.cpp"
#include "Exception_FileCannotOpen.cpp"
#include "Exception_FirstTimeUser.cpp"
#include "Exception_InvalidCommand.cpp"

#include "Logic.cpp"
#include "Commons.cpp"
#include "Task.cpp"
#include "Command.cpp"
#include "Command_Add.cpp"
#include "Command_Clear.cpp"
#include "Command_Edit.cpp"
#include "Command_Exit.cpp"
#include "Command_Help.cpp"
#include "Command_Invalid.cpp"
#include "Command_Redo.cpp"
#include "Command_SaveDirectory.cpp"
#include "Command_Search.cpp"
#include "Command_Undo.cpp"
#include "Command_ViewType.cpp"

#include "Memory.h"
#include "Memory.cpp"
#include "Settings.h"
#include "Settings.cpp"
#include "RAM.h"
#include "RAM.cpp"
#include "Storage.h"
#include "Storage.cpp"

#include "UserInterface.cpp"
#include "CommandFeedback.cpp"
#include "ViewType.cpp"
#include "ViewType0.cpp"
#include "ViewType1.cpp"
#include "ViewType2.cpp"
#include "ViewType3.cpp"

#include "SynonymList.h"
#include "SynonymList.cpp"
#include "Dictionary.h"
#include "Dictionary.cpp"
#include "InputTokens.h"
#include "InputTokens.cpp"
#include "ChronoInterpreter.h"
#include "ChronoInterpreter.cpp"
#include "TaskPacker.h"
#include "TaskPacker.cpp"
#include "CommandPacker.h"
#include "CommandPacker.cpp"
#include "Parser_Interface.h"
#include "Parser_Interface.cpp"
#include "Parser.h"
#include "Parser.cpp"

#endif